### ISSUE TITLE
Where to get the 'vertices.txt'

### ISSUE THREAD

**Issue by deyingk** [nogu-atsu/NARF#2]
Hi,
Thanks for your great work! I was trying to run some experiments, but encountered an error due to the non-existence of the file 'vertices.txt'. Do you know where I can get a copy of this file?
Thanks for your help!

https://github.com/nogu-atsu/NARF/blob/c8eec4c4b1ee403d6d341d657b116a06ce4655e2/data/THUman/util.py#L129

**Comment by nogu-atsu** [comment]
Hi,
Thank you for the question.
It can be downloaded from https://github.com/ZhengZerong/DeepHuman/blob/master/vertices.txt

Please let me know if there are any other problems.

**Comment by deyingk** [comment]
It worked. Thanks so much!
